packages:
  - ansible-lint
  - bind9-dnsutils
  - btop
  - ca-certificates
  - cifs-utils
  - curl
  - fio
  - gh
  - git
  - git
  - gnupg
  - htop
  - just
  - net-tools
  - nfs-common
  - python3-passlib
  - rsync
  - sl
  - software-properties-common
  - stress
  - tmux
  - tree
  - unzip
  - xclip

ssh_config:
  - "Host *"
  - "   StrictHostKeyChecking no"
