packages:
  - ansible-lint
  - bind9-dnsutils
  - btop
  - ca-certificates
  - cifs-utils
  - curl
  - fio
  - gh
  - git
  - git
  - gnupg
  - htop
  - just
  - net-tools
  - nfs-common
  - python3-passlib
  - rsync
  - sl
  - software-properties-common
  - stress
  - tmux
  - tree
  - unzip
  - xclip
  - ncdu

personal_devices:
  - dan-desktop
  - dan-thinkpad
  - ldnvdiprd1
  - ldnvdiprd2
  - ldnvditst1
  - ldnvditst2
  - mcrvdiprd1
  - mcrvdiprd3
  - dan-linux