- name: Clone Required Git Repositories
  ansible.builtin.git:
    repo: "{{ item }}"
    dest: "{{ base.git_directory }}/{{ item | basename }}"
    update: true
  with_items: "{{ base.git_repositories }}"
  async: 60
  poll: 0
  tags: git
  changed_when: false
