- name: SSH | Create Directories
  ansible.builtin.file:
    path: "/home/{{ base.username }}/.ssh"
    state: directory
    mode: '0700'
    owner: "{{ base.username }}"
    group: "{{ base.username }}"

- name: SSH | Download Keys
  ansible.builtin.get_url:
    url: "{{ item.path }}"
    dest: "/home/{{ base.username }}/.ssh"
    mode: "{{ item.mode }}"
    owner: "{{ base.username }}"
    group: "{{ base.username }}"
    url_username: "{{ base.username }}"
    url_password: "{{ ansible_sudo_pass }}"
  with_items:
    - path: "{{ ssh.private_key_url }}"
      mode: 0600
    - path: "{{ ssh.public_key_url }}"
      mode: 0644
