- name: SSH | Create Directories
  ansible.builtin.file:
    path: "/home/{{ base.username }}/.ssh"
    state: directory
    mode: '0700'
    owner: "{{ base.username }}"
    group: "{{ base.username }}"

- name: SSH | Download Private Key
  ansible.builtin.get_url:
    url: "{{ ssh.private_key_url }}"
    dest: "/home/{{ base.username }}/.ssh"
    mode: '0600'
    owner: "{{ base.username }}"
    group: "{{ base.username }}"

- name: SSH | Download Public Key
  ansible.builtin.get_url:
    url: "{{ ssh.public_key_url }}"
    dest: "/home/{{ base.username }}/.ssh"
    mode: '0644'
    owner: "{{ base.username }}"
    group: "{{ base.username }}"
