default:
	just --list

# List current dir using tree
[no-cd]
ls:
	tree . -L 1
# Set Power Mode to High Performance
phigh:
	powershell.exe 'powercfg /setactive SCHEME_MIN'
# Set Power Mode to Balanced
pmid:
	powershell.exe 'powercfg /setactive SCHEME_BALANCED'
# Set Power Mode to Power Saver
plow:
	powershell.exe 'powercfg /setactive SCHEME_MAX'
# Get Power Mode
pget:
	powershell.exe 'powercfg /getactivescheme' && echo ""

#git
git:
	cd ~/git/client-config && ./scripts/gitea_repositories.sh

#wsl
wsl:
	cd ~/git/client-config && ./scripts/setup_wsl.sh
