base:
  git_directory: "~/git/"
  enable_oh_my_posh: false
  enable_starship: true
  enable_az_cli: false
  enable_docker: true
  enable_terraform: true
  enable_ssh_key_config: true
  username: dan

ssh:
  private_key_url: https://files.epichouse.co.uk/SSH/id_rsa
  public_key_url: https://files.epichouse.co.uk/SSH/id_rsa.pub
