base:
  configure_known_hosts: true
  known_hosts: ""
  username: ""
  git_name: ""
  git_email: ""
  git_directory: "~/git/"
  enable_oh_my_posh: false
  enable_az_cli: false
  enable_docker: true
  enable_terraform: true
