base:
  enable_oh_my_posh: false
  enable_az_cli: true
  enable_docker: true
  enable_terraform: true
  enable_ssh_key_config: false
  username: ""
  git_name: ""
  git_email: ""
  git_directory: "~/git/"
oh_my_posh:
  theme: powerlevel10k_lean

ssh:
  private_key_url: "https://files.internal.epichouse.co.uk/SSH/id_rsa"
  public_key_url: "https://files.internal.epichouse.co.uk/SSH/id_rsa.pub"
