- name: Corporate WSL Configuration
  hosts: localhost
  connection: local
  vars_files:
    - ../vars.yml
  tasks:
    - name: WSL Base Configuration
      ansible.builtin.include_role:
        name: wsl_base
    - name: Just Installation
      ansible.builtin.include_role:
        name: just
    - name: Oh My Posh Installation
      ansible.builtin.include_role:
        name: oh_my_posh
      when: base.enable_oh_my_posh
